function telemetry_functional_test
% Send a real MATLAB telemetry breadcrumb after checking phantom availability.

test_dir = fileparts(mfilename('fullpath'));
repository_root = fileparts(fileparts(test_dir));
dicom_source = fullfile( ...
    repository_root, ...
    'OpenNeuroPET-Phantoms', ...
    'sourcedata', ...
    'SiemensBiographPETMR-NIMH', ...
    'AC_TOF');

if ~isfolder(dicom_source)
    error( ...
        'PET2BIDS:MissingPhantoms', ...
        ['OpenNeuroPET phantom data not found. Run ' ...
         '`make collectphantoms decompressphantoms` from the repository root.']);
end

old_ci = getenv('CI');
old_telemetry_enabled = getenv('TELEMETRY_ENABLED');
cleanup = onCleanup(@() restore_environment(old_ci, old_telemetry_enabled));
setenv('CI', 'false');
setenv('TELEMETRY_ENABLED', 'true');

project = "openneuropet/testing_endpoint";
token = string(getenv('MIGAS_TEST_TOKEN'));
if strlength(token) > 0
    auth_options = weboptions( ...
        'HeaderFields', {'Authorization', ['Bearer ' char(token)]}, ...
        'Timeout', 5);
    projects_response = webread( ...
        'https://migas.openneuropet.org/api/auth/projects', ...
        auth_options);
    assert(any(string(projects_response.projects) == project), ...
        ['Migas project ' char(project) ...
         ' is not registered or the test token cannot access it.']);
end

telemetry_data.returncode = 0;
telemetry_data.InputType = 'DICOM';
response = telemetry( ...
    telemetry_data, ...
    string(dicom_source), ...
    "", ...
    project, ...
    "https://migas.openneuropet.org/api/breadcrumb?wait=true");

assert(isstruct(response), 'Migas request failed before receiving a response.');
assert(isfield(response, 'success') && response.success, ...
    'Migas did not accept the MATLAB testing breadcrumb.');
end


function restore_environment(old_ci, old_telemetry_enabled)
setenv('CI', old_ci);
setenv('TELEMETRY_ENABLED', old_telemetry_enabled);
end
