#! /usr/bin/env python

import subprocess
import sys
import os

# get directory this script is called from, it is assumed it is called from the main project dir file where the main Makefile lives (PET2BIDS)
cwd = os.getcwd()

# collect arguments following the calling of this script
python_library = sys.argv[1]

# add dependency to toml file
command = f"cd pypet2bids && poetry add {python_library}"
subprocess.run(command, shell=True)

# update requirements.txt file
command = f"cd pypet2bids && poetry export -f requirements.txt --output requirements.txt --without-hashes"
subprocess.run(command, shell=True)
