#! /usr/bin/env python
import subprocess
import sys

# collect arguments following the calling of this script
python_library = input("Enter name of python library: ")

# add dependency to pyproject.toml file
command = f"cd pypet2bids && uv add {python_library}"
print(f"Updating dependencies:\n{command}")
uv_add = subprocess.run(command, shell=True)

if uv_add.returncode == 0:
    print(f"{python_library} added successfully to pyproject.toml")
else:
    sys.exit(1)
