#!/usr/bin/env bash

# Install project + dev extras (includes gdown for optional downloads)
pushd pypet2bids
uv sync --extra dev
# Uninstall pypet2bids if it exists
uv pip uninstall pypet2bids

# activate pypet2bids virtual environment
source .venv/bin/activate

popd


# Package Library
make buildpackage

# Install package
make installpackage

# Collect Phantoms
PHANTOM_ZIP_FILE=PHANTOMS.ZIP
export $GDRIVE_PHANTOM_ID
if [ -f $PHANTOM_ZIP_FILE ]; then
  echo "$PHANTOM_ZIP_FILE exists, skipping download..."
else
  wget -O PHANTOMS.zip https://openneuropet.s3.amazonaws.com/US-sourced-OpenNeuroPET-Phantoms.zip
fi

# cleanup old run of conversions
rm -rf OpenNeuroPET-Phantoms

# Unzip Phantoms
unzip -oq PHANTOMS.zip

# run conversions on phantoms dataset
cp scripts/matlab_conversions.m OpenNeuroPET-Phantoms/code/matlab_conversions.m
cp scripts/python_conversions.sh OpenNeuroPET-Phantoms/code/python_conversions.sh
pushd OpenNeuroPET-Phantoms/code/
bash python_conversions.sh
popd

# copy dataset description file over
pushd OpenNeuroPET-Phantoms
cp dataset_description.json python/
popd

# Validate
deno run -ERWN jsr:@bids/validator OpenNeuroPET-Phantoms/python --ignoreWarnings --verbose
