#!/usr/bin/env bash

# Install poetry and gdown
pip install poetry gdown

pushd pypet2bids
poetry shell
popd

# Uninstall pypet2bids if it exists
pip uninstall pypet2bids -y

# Package Library
make buildpackage

# Install package
make installpackage

# Collect Phantoms
GDRIVE_PHANTOM_ID=$(grep GDRIVE_PHANTOM_ID pypet2bids/.env)
export $GDRIVE_PHANTOM_ID
gdown $GDRIVE_PHANTOM_ID -O PHANTOMS.zip

# Unzip Phantoms
unzip -oq PHANTOMS.zip

# run conversions on phantoms dataset
cp scripts/matlab_conversions.m OpenNeuroPET-Phantoms/code/matlab_conversions.m
cp scripts/python_conversions.sh OpenNeuroPET-Phantoms/code/python_conversions.sh
pushd OpenNeuroPET-Phantoms/code/
bash python_conversions.sh
popd

# copy dataset description file over
pushd OpenNeuroPET-Phantoms
cp dataset_description.json python/
popd

# Validate 
bids-validator OpenNeuroPET-Phantoms/python

